@echo off
IF EXIST "../synth/__projnav" rmdir /S /Q "../synth/__projnav" 
IF EXIST "../synth/xst" rmdir /S /Q "../synth/xst" 
IF EXIST "../synth/_ngo" rmdir /S /Q "../synth/_ngo" 

IF EXIST _xmsgs rmdir /S /Q _xmsgs
IF EXIST icon_xdb rmdir /S /Q icon_xdb
IF EXIST ila_xdb rmdir /S /Q ila_xdb
IF EXIST tmp rmdir /S /Q tmp
IF EXIST vio_xdb rmdir /S /Q vio_xdb
IF EXIST xlnx_auto_0_xdb rmdir /S /Q xlnx_auto_0_xdb

IF EXIST coregen.cgp del /F /Q coregen.cgp
IF EXIST coregen.cgc del /F /Q coregen.cgc
IF EXIST coregen.log del /F /Q coregen.log
IF EXIST icon.asy del /F /Q icon.asy
IF EXIST icon.gise del /F /Q icon.gise
IF EXIST icon.ise del /F /Q icon.ise
IF EXIST icon.ngc del /F /Q icon.ngc
IF EXIST icon.xco del /F /Q icon.xco
IF EXIST icon.xise del /F /Q icon.xise
IF EXIST icon_flist.txt del /F /Q icon_flist.txt
IF EXIST icon_readme.txt del /F /Q icon_readme.txt
IF EXIST icon_xmdf.tcl del /F /Q icon_xmdf.tcl

IF EXIST ila.cdc del /F /Q ila.cdc
IF EXIST ila.gise del /F /Q ila.gise
IF EXIST ila.ise del /F /Q ila.ise
IF EXIST ila.ngc del /F /Q ila.ngc
IF EXIST ila.xco del /F /Q ila.xco
IF EXIST ila.xise del /F /Q ila.xise
IF EXIST ila_flist.txt del /F /Q ila_flist.txt
IF EXIST ila_readme.txt del /F /Q ila_readme.txt
IF EXIST ila_xmdf.tcl del /F /Q ila_xmdf.tcl

IF EXIST vio.cdc del /F /Q vio.cdc
IF EXIST vio.gise del /F /Q vio.gise
IF EXIST vio.ise del /F /Q vio.ise
IF EXIST vio.ngc del /F /Q vio.ngc
IF EXIST vio.xco del /F /Q vio.xco
IF EXIST vio.xise del /F /Q vio.xise
IF EXIST vio_flist.txt del /F /Q vio_flist.txt
IF EXIST vio_readme.txt del /F /Q vio_readme.txt
IF EXIST vio_xmdf.tcl del /F /Q vio_xmdf.tcl


IF EXIST ise_flow_results.txt del /F /Q ise_flow_results.txt
IF EXIST mem_interface_top.syr del /F /Q mem_interface_top.syr
IF EXIST smartpreview.twr del /F /Q  smartpreview.twr

IF EXIST ddrneu.bgn del /F /Q  ddrneu.bgn
IF EXIST ddrneu_bitgen.xwbt del /F /Q  ddrneu_bitgen.xwbt
IF EXIST ddrneu.bit del /F /Q  ddrneu.bit
IF EXIST ddrneu.bld del /F /Q ddrneu.bld
IF EXIST ddrneu.drc del /F /Q  ddrneu.drc
IF EXIST ddrneu.ncd del /F /Q  ddrneu.ncd
IF EXIST ddrneu.ngc del /F /Q ddrneu.ngc
IF EXIST ddrneu_prev_built.ngd del /F /Q ddrneu_prev_built.ngd
IF EXIST ddrneu.ngd del /F /Q ddrneu.ngd
IF EXIST ddrneu.ngr del /F /Q ddrneu.ngr
IF EXIST ddrneu.pad del /F /Q  ddrneu.pad
IF EXIST ddrneu.par del /F /Q  ddrneu.par
IF EXIST ddrneu.pcf del /F /Q  ddrneu.pcf
IF EXIST ddrneu.ptwx del /F /Q  ddrneu.ptwx
IF EXIST ddrneu.twr del /F /Q  ddrneu.twr
IF EXIST ddrneu.twx del /F /Q  ddrneu.twx
IF EXIST ddrneu.unroutes del /F /Q  ddrneu.unroutes
IF EXIST ddrneu.ut del /F /Q  ddrneu.ut
IF EXIST ddrneu.xpi del /F /Q  ddrneu.xpi
IF EXIST ddrneu_map.map del /F /Q  ddrneu_map.map
IF EXIST ddrneu_map.mrp del /F /Q  ddrneu_map.mrp
IF EXIST ddrneu_map.ncd del /F /Q  ddrneu_map.ncd
IF EXIST ddrneu_map.ngm del /F /Q  ddrneu_map.ngm
IF EXIST ddrneu_map.xrpt del /F /Q  ddrneu_map.xrpt
IF EXIST ddrneu_ngdbuild.xrpt del /F /Q  ddrneu_ngdbuild.xrpt
IF EXIST ddrneu_pad.csv del /F /Q  ddrneu_pad.csv
IF EXIST ddrneu_pad.txt del /F /Q  ddrneu_pad.txt
IF EXIST ddrneu_par.xrpt del /F /Q  ddrneu_par.xrpt
IF EXIST ddrneu_summary.xml del /F /Q  ddrneu_summary.xml
IF EXIST ddrneu_usage.xml del /F /Q  ddrneu_usage.xml
IF EXIST ddrneu_vhdl.prj del /F /Q ddrneu_vhdl.prj
IF EXIST ddrneu_xst.xrpt del /F /Q ddrneu_xst.xrpt

:: Files and folders generated by create ise
IF EXIST xst rmdir /S /Q xst 
IF EXIST _ngo rmdir /S /Q _ngo
IF EXIST test_xdb rmdir /S /Q test_xdb 
IF EXIST _xmsgs rmdir /S /Q _xmsgs 
IF EXIST test.ntrc_log del /F /Q test.ntrc_log
If EXIST ddrneu.cmd_log del /F /Q ddrneu.cmd_log
IF EXIST ddrneu.lso del /F /Q  ddrneu.lso
IF EXIST ddrneu.ngc del /F /Q ddrneu.ngc
IF EXIST ddrneu.prj del /F /Q  ddrneu.prj
IF EXIST ddrneu.stx del /F /Q ddrneu.stx
IF EXIST ddrneu.syr del /F /Q ddrneu.syr
IF EXIST ddrneu.xst del /F /Q ddrneu.xst
IF EXIST ddrneu_summary.html del /F /Q  ddrneu_summary.html
IF EXIST ddrneu_usage.html del /F /Q  ddrneu_usage.html
IF EXIST ddrneu_prev_built.xst del /F /Q ddrneu_prev_built.xst
IF EXIST ddrneu_summary.xst del /F /Q ddrneu_summary.xst
IF EXIST par_usage_statistics.html del /F /Q par_usage_statistics.html
IF EXIST usage_statistics_webtalk.html del /F /Q usage_statistics_webtalk.html
IF EXIST webtalk.log del /F /Q webtalk.log
IF EXIST device_usage_statistics.html del /F /Q	device_usage_statistics.html
IF EXIST ddrneu_guide.ncd del /F /Q  ddrneu_guide.ncd
IF EXIST test.gise del /F /Q test.gise
IF EXIST test.xise del /F /Q test.xise
IF EXIST test.xise del /F /Q test.xise

@echo on
